# Generated by Django 4.2 on 2024-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('słodycze i ciasta', 'Słodycze i ciasta'), ('zupy', 'Zupy'), ('dania główne', 'Dania główne')], max_length=50, unique=True),
        ),
    ]
